### ISSUE TITLE
Irregular space on generated code

### ISSUE THREAD

**Issue by jcristovao** [kristiandupont/kanel#11]
I think the issue is on this line (obtained with `cat -e -n src/generateInterface.js | head -n 55 | tail -n 10`):

```
   51    const typeStr =$
   52      nullable && !considerDefaultValue ? `${rawType} |M-BM- null` : rawType;$
```

Any particular reason the `null` is not preceded by a regular space? Or was it just a typo?

**Comment by kristiandupont** [comment]
I'm sorry, I don't think I understand. It is preceded by an irregular space?

**Comment by kristiandupont** [comment]
I understand now. I think it's an issue with VSCode Vim actually. I've fixed this issue. I should probably add the option to run Prettier on generated files.

**Comment by bostrom** [comment]
Running prettier on all generated files would be useful! 

Something like Orval's `afterAllFilesWrite` perhaps? https://orval.dev/reference/configuration/hooks#afterallfileswrite perhaps

**Comment by kristiandupont** [comment]
Yes, exactly!
