### ISSUE TITLE
Unrecognized types when generating model using array types: 'date[]' and 'text[]'

### ISSUE THREAD

**Issue by xavier-taylor** [kristiandupont/kanel#111]
Hi there!

Thanks for putting out this great library. 

I got the following errors when generating types for my schema tonight.
```
Unrecognized type: 'text[]'
Unrecognized type: 'date[]'
```

My schema uses the postgres [array type](https://www.postgresql.org/docs/9.1/arrays.html), ie 
``` studyInstances  date[] NOT NULL,```.

Fortunately, I could resolve this error by adding the following to my kanelrc.js
```
  customTypeMap: {
    "text[]": "string[]",
    "date[]": "Date[]",
  },
```

I am just leaving this issue here for two reasons:
1. so other people with a similar problem can see how your excellent library provides a simple solution for issues like this, and
2. In case you weren't aware of this kind of issue, so you could address it if that is something you are interested in doing.

Sorry I don't have the time to submit a PR myself, and once again, thanks for saving me many hours by providing this code :)

**Comment by kristiandupont** [comment]
This does look like something that ought to work out of the box, so I will make a fix for it. Thank you for the heads up, and for the kind words!

**Comment by kristiandupont** [comment]
This should finally be addressed :-)

There is a premajor version out that should fix this issue. There are significant breaking changes though, and the API is not final so feel free to experiment if you like. The documentation is work in progress still, you can start here:
https://github.com/kristiandupont/kanel/blob/v3/docs/configuring.md

**Comment by kaliq-i** [comment]
Too many breaking changes to resolve purely by migration to v3, is there a fix you can recommend for those still on v2
