### ISSUE TITLE
db connection not closed

### ISSUE THREAD

**Issue by JoshRagem** [kristiandupont/kanel#114]
the knex db connection is not exposed or closed, so using kanel programmatically results in a leaked connection and a hang on exit

**Comment by kristiandupont** [comment]
Yes, this is an embarrassing bug. It exists because I used to run [Schemalint](https://github.com/kristiandupont/schemalint) and Kanel in the same script, using the same Knex instance. I didn't really clean up properly when extracting them, I will fix this.

**Comment by kristiandupont** [comment]
This is fixed in the newly deployed version
