### ISSUE TITLE
Change `__flavor` to `__model`? 

### ISSUE THREAD

**Issue by rattrayalex** [kristiandupont/kanel#126]
I know the technique may be called flavoring, but it feels weird to refer to a table class as a flavor – it's a table! or a model, or a "class", etc.
What do you think?

**Comment by kristiandupont** [comment]
I am not sure I agree that it's really a table or a model, it's a (somewhat unique) identifier that can helpfully refer to the context where it will be used. 

Since it's become a de facto standard to call those `__brand` when using branded typing, I think the `__flavor` name makes sense.

**Comment by rattrayalex** [comment]
Hmm, fair… what do you think about `__id`?
```ts
export type ActorId = number & { __id?: 'actor' };
```
Or maybe `__type` or `__idOf` or `__idFor` or `__for`?

I just don't want to be thinking about ice cream while coding – my models aren't necessarily flavorful 😅

**Comment by kristiandupont** [comment]
I've created a config option `makeIdType` that can be a function. It takes the inner type and the model name and should return the string for the type you want. I hope this solves it :-)

**Comment by rattrayalex** [comment]
Nice, works for me! Too bad about the quotes, they're kinda ugly, but I get it. Would probably also be good to have the feature documented in the readme.
