### ISSUE TITLE
Add /* @generated */ pragma

### ISSUE THREAD

**Issue by zth** [kristiandupont/kanel#131]
Hi!

Would it be possible to add a `/* @generated */` comment on top of each generated file? This will help hide the generated files in PRs/diffs, etc.

**Comment by kristiandupont** [comment]
Yeah, that would be fairly simple. Is that a standard of some sort?

**Comment by zth** [comment]
I'm unsure tbh exactly how standardized it is, but I know both GitHub and Phabricator supports it in their diffs. Maybe it could be a config option?

**Comment by kristiandupont** [comment]
Should work in the new release.

**Comment by zth** [comment]
@kristiandupont thank you very much!
