### ISSUE TITLE
Generate knex table -> Type mapping

### ISSUE THREAD

**Issue by janmeier** [kristiandupont/kanel#17]
Recently (as in, four days ago), knex released an option to automagically map table names to return types:

https://github.com/knex/knex/pull/4071

In practice, this means that with an interface definition like this: 
```ts
declare module 'knex/types/tables' {
  interface Tables {
    [Table.Profile]: IProfile
    [Table.FitnessPackage]: IFitnessPackage
  }
}
```

Knex can infer the returnType when doing `knex(tableName)`

![image](https://user-images.githubusercontent.com/1210224/98121243-56d76980-1eaf-11eb-9c84-79699409a0af.png)
```ts
await knex(Table.Profile).innerJoin(
    Table.FitnessPackage,
    `${Table.FitnessPackage}.id`,
    `${Table.WorkoutPlan}.fitness_package_id`,
  )
```

As seen in the snippet / screenshot, this supports joins as well.

Since kanel already knows the names of the tables and their corresponding types, I think this would be a very nice addition. WDYT?
I can look into providing a PR if you think this would be a good addition

**Comment by janmeier** [comment]
cc @cem2ran

**Comment by kristiandupont** [comment]
I think that's the `modelTypeMap`: https://github.com/kristiandupont/kanel/blob/master/example/models/index.ts#L48, isn't it?
It should really be extracted from the index file though -- that file is a mess..

**Comment by janmeier** [comment]
Sure, sound exactly like what we want - I'm not very familiar with typescript, but it should be possible to import tap map from kanel and export it as knex expects (`declare module 'knex/types/tables' {  interface Tables ... `)
