### ISSUE TITLE
bigint (int8) mapped to Javascript number

### ISSUE THREAD

**Issue by xavier-taylor** [kristiandupont/kanel#170]
Hey mate,

I noticed in https://github.com/kristiandupont/kanel/blob/master/src/defaultTypeMap.ts that int8 is mapped to a javascript number. However, I believe the javascript number type cannot support as large integer values as bigint/int8. If I am correct, it might be safer to map that type to string.

**Comment by kristiandupont** [comment]
Yes, this is a long-standing issue. I will change to string and let people override as they please. Thank you reminding me! :-)

**Comment by kristiandupont** [comment]
This is fixed.
