### ISSUE TITLE
Transform function for type's names

### ISSUE THREAD

**Issue by Ericnr** [kristiandupont/kanel#18]
It's a common convention for database tables to have plural names, eg. "users", so Kanel will generate a "Users" type for the table, which goes against TS conventions. Id ask for a config options to address exactly this, but converting a word for plural to singular isn't as simple removing an `s`, so a lower level transform function should be simple and appease many more use cases.

**Comment by kristiandupont** [comment]
Yes, I've run into this as well. I have an inflection check [rule](https://github.com/kristiandupont/schemalint/blob/master/src/rules/nameInflection.js) in Schemalint and this feels like the natural extension of it. I guess there should be a fallback table->class name mapping or even function so people can override in other ways? Or is that solving a problem that nobody has? :-)

**Comment by Ericnr** [comment]
a table to type name map sounds like a good solution! Im sure more people will run into this too

**Comment by kristiandupont** [comment]
This is possible now. The configuration takes properties `modelNominator` and `typeNominator` -- you can give it functions that does the transformation. I don't know if there is an unofficial standard library for inflection on NPM, but I guess you can easily write it yourself with whatever special cases you might have :-)
Let me know if it works for you!

**Comment by Ericnr** [comment]
yep, that works great!
