### ISSUE TITLE
Strange bug where a column is omitted from the initializer interface

### ISSUE THREAD

**Issue by Ericnr** [kristiandupont/kanel#20]
I have createdAt and an updatedAt columns which are identical in SQL, but the createdAt field is omitted from the initializer interface. This happens with multiple different tables.
```ts
interface Customers {
  /** Primary key. Index: customers_pkey */
  id: CustomersId;

  name: string;

  email: string | null;

  createdAt: Date;

  updatedAt: Date;
}

interface CustomersInitializer {
  /**
   * Default value: uuid_generate_v4()
   * Primary key. Index: customers_pkey
  */
  id?: CustomersId;

  name: string;

  email?: string;

  // createdAt is omitted.

  /** Default value: CURRENT_TIMESTAMP */
  updatedAt?: Date;
}
```
Not a huge problem since I dont ever want to set createdAt manually, but it seems like a bug

**Comment by kristiandupont** [comment]
lol that's actually on purpose because I have code that sets those explicitly. It's clearly a bug at this level though, I'll remove the custom check from Kanel and move it to my own code base.

**Comment by kristiandupont** [comment]
This is fixed now.
