### ISSUE TITLE
[Suggestion] Feedback after running kanel

### ISSUE THREAD

**Issue by jcamato** [kristiandupont/kanel#256]
I set up my environment exactly the same as the example. After executing `npx kanel` nothing happens, and I don't get any errors or messages. My database has 73 tables, so I'm not sure if it's taking a while to process these or if my implementation is incorrect. However, the README was pretty straightforward so I don't think it's that.

edit: I was able to generate the models through the programmatic example. (I had to add the dot prefix on import) `import config from '../database/.kanelrc';`

**Comment by kristiandupont** [comment]
Hi jcamato, I am sorry to hear that! But happy that it worked out with the programmatic way. I guess I haven't tried running the example in a while so maybe I have broken something with it when developing features. I will look into it!

**Comment by jcamato** [comment]
No worries, thank you @kristiandupont for a neat tool!
