### ISSUE TITLE
Does not work with Citext

### ISSUE THREAD

**Issue by joshua1** [kristiandupont/kanel#272]
Hi @kristiandupont , i use the citext extension in my DB and have text column with citext as the data type. can this be included in the type conversion to string alongside Varchar,text, uuid.
Thanks

**Comment by joshua1** [comment]
I just saw the custom type mapping in config example. I will try with that

**Comment by kristiandupont** [comment]
I am looking into a more general purpose handling of domains. It's annoying because the PG type concepts don't map to TS that well. But I am happy that the workaround works for you for now.
