### ISSUE TITLE
Generates types with syntax error when column name contains `-`

### ISSUE THREAD

**Issue by darvesh** [kristiandupont/kanel#285]
As the title says, if there is `-` in the column name, it doesn't wrap it in quotes.

**Comment by kristiandupont** [comment]
Right. This happens to work in [version 3](https://github.com/kristiandupont/kanel/pull/266) which I am working on. Feel free to play around with it though note that there are several breaking changes and the API might still change a bit if people request it.

https://www.npmjs.com/package/kanel/v/3.0.0-0

**Comment by kristiandupont** [comment]
(Oh and note that the README is not yet updated there! :-D But you can see the documentation here: https://github.com/kristiandupont/kanel/blob/v3/docs/configuring.md

**Comment by darvesh** [comment]
I'll check it out. Thank you for the swift response, and creating this wonderful tool.
