### ISSUE TITLE
v3 does not generate index file?

### ISSUE THREAD

**Issue by sleewoo** [kristiandupont/kanel#288]
Hello,
congrats on releasing v3!

Would you consider bring this functionality back?
Perhaps pre/post hooks can be used to generate index file.
But generating it by adding to config some option like `generateIndexFile` would be great! :)

Thanks.

**Comment by sleewoo** [comment]
sorry, missed `hooks/generateIndexFile`,
that's great there is an example in the repo.

**Comment by kristiandupont** [comment]
Happy you found it and yes, I need to add documentation about it! Let me know if anything else is broken, it's quite a big rewrite so I hope it still works for everyone :-)

**Comment by sleewoo** [comment]
seems `recase` called on runtime,
should you move it to `dependencies`?

**Comment by kristiandupont** [comment]
I should! Thank you :-D

**Comment by kristiandupont** [comment]
Done.
