### ISSUE TITLE
Enums exported as Typescript Types when using `preRenderHooks: [generateIndexFile]`

### ISSUE THREAD

**Issue by hexcowboy** [kristiandupont/kanel#292]
Kanel properly generates enums for Postgres enum types

```ts
enum ListenerType {
  ethereum = 'ethereum',
};
```

But when using the `generateIndexFile` hook, it exports it as a type

```ts
export type { default as ListenerType } from './public/ListenerType';
```

So it can't be used like so:

```ts
ListenerType.ethereum
// 'ListenerType' cannot be used as a value because it was exported using 'export type'.
```

**Comment by kristiandupont** [comment]
Nice catch! Kanel used to generate "enums" as literal string types which would not have caused this. I think I might make that an option but for now, your PR fixes this as far as I can tell.
