### ISSUE TITLE
Would be great if it could analyze jsonb columns and prepare proper types

### ISSUE THREAD

**Issue by pie6k** [kristiandupont/kanel#3]
I know it would complicate things by a lot, but in our project, we have some custom data from the client that cannot be simply mapped to atomic columns, so we keep them inside a single, jsonb column.

It would be awesome if this could walk such table and collect types from those and create a type for the entire column

**Comment by kristiandupont** [comment]
Hm. So there is support for non-generated types. If you set the comment on a column to something like this: `"This represents the users in the system. @type:User"`, it will use the type `User` and import that from a folder above the models folder, so you can create it there yourself.

There is also a json schema validation plugin for postgres that I have been looking at: https://github.com/gavinwahl/postgres-json-schema. Unfortunately, I don't have experience with using such plugins on hosted providers and I am not sure it's possible so that isn't necessarily the most viable way either.

I suppose it would be possible to scan every row and set the type to be the union of all of the extracted types but that feels a bit backwards to me. Would that be the only way to decide the type for you?

**Comment by chapmanjacobd** [comment]
This is an interesting question. If you have a schema which is consistent enough to be a type then ideally you wouldn't have it in a JSON/B column. Performance of a JSONB column will never match normal relational data structures. 

**If the data has no common structure then a type which represents the data structure will never be smaller than the data itself**. But maybe some of these queries will help:

https://dba.stackexchange.com/questions/203250/getting-specific-key-values-from-jsonb-into-columns
https://stackoverflow.com/questions/36141388/how-can-i-get-all-keys-from-a-json-column-in-postgres
https://stackoverflow.com/questions/36575991/get-array-of-all-json-field-keys-in-postgresql
https://stackoverflow.com/questions/45280571/getting-json-field-key-names-in-postgres
https://dba.stackexchange.com/questions/226914/extract-all-of-the-keys-including-nested-from-postgres-jsonb-column
https://stackoverflow.com/questions/39991315/select-or-extract-all-key-values-inside-a-jsonb-data-in-postgres
https://stackoverflow.com/questions/46494856/how-to-get-only-the-jsonb-of-specific-keys-from-postgres
https://stackoverflow.com/questions/56017008/postgresql-get-keys-from-array-of-objects-in-jsonb-field
https://stackoverflow.com/questions/39042151/postgres-jsonb-get-values-of-key-from-multidimentional-array

**Comment by kristiandupont** [comment]
This seems like an interesting experiment. I wonder if I should consider a way to enable a plugin that does this..

**Comment by jifeon** [comment]
+1 to have this feature.

I totally agree with @chapmanjacobd , but sometimes when the speed of development decides if a company will survive, jsonb really helps by allowing front-end to store a lot of stuff without backend development. We now migrating a huge project to TS and we have dozens of tables using JSONB fields which would be very nice to validate with TS. 

We have postgres models which `implements` types generated by `kanel`, so for now I'm going to redefine these types on models level, but it would be cool to store the types with postgres itself.

**Comment by kristiandupont** [comment]
I see where you are coming from. I still wonder though, if this belongs in here or in a separate tool. For instance, such a type inferencer wouldn't be able to decide if a string field is an enum or a general-purpose string. And how would it know which fields are required? None? Or any that are present in every row? 

All of this, to me, seems like something I would want a tool for but as a first step. It would tell me: this is what a type _might_ look like, but you should edit it and then add it to your library. Or do you see this as something you would run continually, just to have a vague idea through intellisense?

**Comment by chapmanjacobd** [comment]
I could build a tool like this. I think it would be difficult to make something that would satisfy what everybody would want this type of tool to do but reach out to me if you have specific requirements.

**Comment by kristiandupont** [comment]
@chapmanjacobd I think that would be great. I will happily link to it from here or even integrate it if you think that makes sense in some way. 

I've extracted Kanel from my codebase at Submotion, where I have more logic that creates some automatic synchronization logic between backend and frontend. I'm looking into open sourcing that code as well and for that, I might need to create a more capable plugin system than the current hooks that are quite limited.

**Comment by kristiandupont** [comment]
I'm closing this for now. If you feel like taking it up again, create a new issue and we can discuss approaches. I will not be able to prioritize it personally, but I would offer help with infrastructure for plugins or more advanced hooks etc.
