### ISSUE TITLE
Wrong Path Generation On Windows System

### ISSUE THREAD

**Issue by VincentLeV** [kristiandupont/kanel#323]
We have setup .kanelrc.js something like this in our project
```
connection,
  outputPath: "../lib/src/db/generated",
  preDeleteOutputFolder: true,
  preRenderHooks: [generateIndexFile],

  customTypeMap: {
    "public.citext": "string",
    "public.uuid": "string",
    "public.text[]": "string[]",
    "public.citext[]": "string[]",
  },

  schemas: ["app_hidden"]
```

In the index.ts file, the generated import is very weird 
<img width="333" alt="image" src="https://user-images.githubusercontent.com/49280437/196124200-aa8c5b0c-9502-489f-b491-bae2cdb714f2.png">

I'm using Windows system and I have this issue but my colleagues use Linux systems and nothing went wrong. Any ideas how to fix this? 

Thank you!

**Comment by kristiandupont** [comment]
Ah, that's a bug that I didn't notice on my Mac. It should be a rather easy fix, let me take a look at it.

**Comment by kristiandupont** [comment]
I've published a new version, try it out and let me know if it helped.

**Comment by VincentLeV** [comment]
I'm sorry to reopen the issue. Today I reseted our database and the wrong paths persist and I couldn't start the server. Could you check this? Thank you!

**Comment by kristiandupont** [comment]
Did you update? I just released a new version a bit ago, I wonder if it's a regression..

**Comment by VincentLeV** [comment]
Yes, I've updated and it worked until i reset the db today...

**Comment by VincentLeV** [comment]
Unfortunately, the app doesn't even get to the `console.log`, it stucks before that 
<img width="953" alt="image" src="https://user-images.githubusercontent.com/49280437/196607497-f4ead87e-4fa6-409a-8718-ad1c0c9fb754.png">

**Comment by VincentLeV** [comment]
I think I made it works now. Sorry for this, I have some pending changes related to kanel and I didn't know it affected the process. So after I undid the changes, kanel ran fine!

**Comment by kristiandupont** [comment]
Okay, that sounds good!

**Comment by dangnhdev** [comment]
> That's really strange. Could you take a look in the `build/hooks/generateIndexFile.js` lines 37-39 -- they should say:
> 
> ```js
>         if (path_1.sep === '\\') {
>             importPath = importPath.replace(/\\/g, '/');
>         }
> ```
> 
> ..And then maybe add a `console.log` statement after it to see if the path looks corrected?

[The latest commit to this file](https://github.com/kristiandupont/kanel/commit/09e46b5680cc099aecfe1a14f9f62b8655f7a9da#diff-a0fbfc58ddd0cec2348ebae92df8acda634e72e34bf88c53667aed5cfe99d83c) removed this line, thus making this issue happen again. Can you please review it?
