### ISSUE TITLE
Errors in strict mode caused by importing types as values

### ISSUE THREAD

**Issue by sleewoo** [kristiandupont/kanel#324]
Hi,
is there an option to make Kanel import types with `type` notation?

When enabling `strict` mode or both `isolatedModules` and `preserveValueImports` are enabled, getting errors like:

```
../db/types/generated/public/CloudflareTokens.ts:4:10 - error TS1444: 'UserId' is a type and must be imported using a type-only import when 'preserveValueImports' and 'isolatedModules' are both enabled.

4 import { UserId } from './Users';
           ~~~~~~
```

Normally error gone if manually/temporarily using `import type { UserId } from './Users';` 

How can one tell Kanel do this on generation?

Thanks.

**Comment by kristiandupont** [comment]
Ah, that's a good point. It's not currently possible but should be a pretty easy fix. I will try to get around to it this week.

**Comment by kristiandupont** [comment]
I've published a version that hopefully fixes this. Try it out and let me know if it works for you.

**Comment by sleewoo** [comment]
works perfect! 👍 
thank you much!
