### ISSUE TITLE
is zod usable?

### ISSUE THREAD

**Issue by mbriggs** [kristiandupont/kanel#343]
Hey :) 

Kanel is a great project! I need zod interfaces, but it seems like kanel-zod is not published yet? Is there still bugs / instability?

Thanks

**Comment by kristiandupont** [comment]
Hi, and thank you for the kind words!

No, Zod support is work in progress. I was going to use it on a project but that stopped so I haven't had any personal motivation :-) I am still planning to make it work though. Are there any specific features you are looking for?

**Comment by kristiandupont** [comment]
Hi @mbriggs,

I've just published a very minimalistic first version. It gets easily confused if you've done a lot of configuration and the documentation is next to non-existent but I figured it would be better to get it out there and get feedback based on real-world usage, so if you want to try it out, you can now. I am obviously very keen to hear your thoughts. 

Cheers!
