### ISSUE TITLE
A type-only import can specify a default import or named bindings, but not both.ts(1363)

### ISSUE THREAD

**Issue by darvesh** [kristiandupont/kanel#358]
<img width="848" alt="image" src="https://user-images.githubusercontent.com/22394081/212740296-f45b9e4e-8fe2-4afb-9054-6aa3d8bd1799.png">

**Comment by kristiandupont** [comment]
Ah, that's an issue, yes. I will look into it.

**Comment by kristiandupont** [comment]
I just published a new version that hopefully fixes your issue. Let me know if it works!

**Comment by darvesh** [comment]
It's working. Thank you.
