### ISSUE TITLE
generateKnexTablesModule issues with default import in strict mode

### ISSUE THREAD

**Issue by sleewoo** [kristiandupont/kanel#360]
Hello,
getting this error when in strict mode:

`A type-only import can specify a default import or named bindings, but not both.`

![Screenshot_20230121_132753](https://user-images.githubusercontent.com/74734701/213864934-61a87609-32b7-4fe1-a75d-b1ec9472ccfa.png)

Ready to "dig" into the code and find a fix.

Thanks.

**Comment by kristiandupont** [comment]
Hm, I thought I fixed it with https://github.com/kristiandupont/kanel/commit/a26e1653fab5a6126b442d2dbbb3b57c85f90ae2 -- are you on the newest version? Otherwise I must have missed something..

**Comment by sleewoo** [comment]
oh, sorry, was on older version,
works perfect,
thank you!
