### ISSUE TITLE
Error on enumStyle=type with --isolatedModules

### ISSUE THREAD

**Issue by sleewoo** [kristiandupont/kanel#361]
Hello,

switched `enumStyle` to `type` and got a bunch of errors like:

```
error TS1205: Re-exporting a type when the '--isolatedModules' flag is provided requires using 'export type'.
```
![Screenshot_20230125_074652](https://user-images.githubusercontent.com/74734701/214489558-fd1d0346-5e12-42d0-b064-e68350d71ef2.png)

Sort of related to prev issues but still not an easy fix to me :)
Yet, ready to submit a PR.
Thanks.

**Comment by sleewoo** [comment]
what if emitting both `Enum` and `Union` styles, but TypeDefinition imports/using only opted style.
so if `enumStyle` set to `type`, there is still `Enum` emitted, but TypeDefinition uses `type`.

though need union for  TypeDefinition, there are many places where i need enum.
and no way to convert union to enum.

**Comment by kristiandupont** [comment]
I think it's just a matter of checking the style in this condition: https://github.com/kristiandupont/kanel/blob/master/packages/kanel/src/hooks/generateIndexFile.ts#L67 -- I don't have time to look into it right now but I will try to get around to it this week.

**Comment by sleewoo** [comment]
thanks for hints, added prefix

**Comment by kristiandupont** [comment]
New version is published, thank you!

**Comment by sleewoo** [comment]
@kristiandupont, sorry for bothering,
what if `enumStyle` option would be ignored on `generateIndexFile`?
i mean whatever `enumStyle` is set to, `generateIndexFile` always exporting enum.

you know, enums are much more practical and can be easily converted to union types.
but if exporting union types, we can not convert them to enums, can not use them at runtime etc.

i have a PR where `enumStyle` used to determine default export to use on type declarations.
but `generateIndexFile` always exports enums as enums.

makes sense?
would you find a minute to review?

**Comment by kristiandupont** [comment]
Hm, I don't think I understand. If the generated types are not `enum`s, how can the index export them as something different? Happy to look at a PR..

**Comment by sleewoo** [comment]
well, enum file is always exporting named enum, regardless enumStyle.
enumStyle only affects the default export, not named one.
and `generateIndexFile` is importing named export, which is always there.

**Comment by sleewoo** [comment]
here it is
https://github.com/kristiandupont/kanel/pull/364

**Comment by sleewoo** [comment]
generated with `enumStyle` = `type`

![Screenshot_20230126_100152](https://user-images.githubusercontent.com/74734701/214785218-6625540a-31e8-49c6-a7a4-c2306f03ab54.png)

**Comment by sleewoo** [comment]
generated with `enumStyle` = `enum`

![Screenshot_20230126_100326](https://user-images.githubusercontent.com/74734701/214785458-765b5434-1712-4449-bc88-88f6e2ead87b.png)

**Comment by sleewoo** [comment]
and index file always render like this, regardless `enumStyle`

![Screenshot_20230126_100616](https://user-images.githubusercontent.com/74734701/214785902-fac192a1-b61a-4588-94ba-3202314f7e2a.png)

**Comment by kristiandupont** [comment]
I am still not sure I understand the benefit of this change. I personally dislike enums but I am aware (from recent Reddit discussions) that it's a controversial topic so I am happy to offer both types. 

What is gained by limiting to only enums? This would be a breaking change that I would personally have to override where I use Kanel because I expect the default exports to be union types.

**Comment by sleewoo** [comment]
you right, this is a matter of taste and needs,
there is no place for enum vs union arguing :)

wonder what would be the best approach to make happy both sides.
if one needs unions - he get unions exported by index file.
f another need enums - he get enums.

**Comment by kristiandupont** [comment]
But isn't that how it is right now? Or is there a bug that I am missing? If you set enum style to `enum`, you get enums? Or is it broken in the index generator? I feel like I am missing something here :-)

**Comment by sleewoo** [comment]
well, maybe it's just me with such needs...
but i need declaration files to use union types, and still be able to use enums.

declaration file:

```ts
status: "pending" | "processing" | "processed" | "failed";
```

index file:

```ts
export { item_status as ItemStatusEnum } from "./public/ItemStatus";
```

this way i get the best of both:
- can use strings for status in knex queries
- can use enums at runtime

**Comment by sleewoo** [comment]
compare, `enumStyle` set to `enum`

then in knex queries looks like

```ts
where({ status: ItemStatusEnum.pending })
```

vs `enumStyle` set to `type`

```ts
where({ status: "pending" })
```

**Comment by sleewoo** [comment]
now to have validated strings in queries i have to sacrifice enums at runtime, which i use a lot

**Comment by sleewoo** [comment]
but you right, it should not be written in stone.

what if adding an extra option - `enumExportStyle`
to determine what would index file export - enums or unions

**Comment by kristiandupont** [comment]
Ah, I think I am starting to understand. Hm. It seems somewhat related to what @zimme is doing in #350. Maybe there is a general pattern here..

**Comment by kristiandupont** [comment]
Alternatively, unions could be created from const arrays:

```typescript
export const statusItems = ['pending', 'processing', 'processed', 'failed'] as const;

type Status = typeof statusItems[number];

export default Status;
```

Would that work in your case?

**Comment by sleewoo** [comment]
quite otherwise,
i need enums exported by index file, not types

**Comment by sleewoo** [comment]
i guess `enumExportStyle` option would cover all scenarios.

when one need unions in declaration files and enums in index file:

```ts
{ enumStyle: 'type', enumExportStyle: 'enum' }
```

when one need enums in declaration files and types in index file:

```ts
{ enumStyle: 'enum', enumExportStyle: 'type' }
```


when one need enums in both declaration files and index file:

```ts
{ enumStyle: 'enum' }
```


when one need unions in both declaration files and index file:

```ts
{ enumStyle: 'type' }
```

**Comment by sleewoo** [comment]
`{ enumStyle: 'type', enumExportStyle: 'enum' }` - with this i get validated strings in knex queries and ability to use enums at runtime.

pretty sure this pattern will be used pretty frequently

**Comment by kristiandupont** [comment]
Can I ask what you need the union types for if you have the enums?

One thing to keep in mind is that the `generateIndexFile` hook is a "plugin" that you can easily replace with your own, and that was more or less my idea. I added it more or less as an example. But of course, if you need both enums and unions exported in the first place, you would need something else. It would be possible (and quite trivial, really) to write another hook that does that which *might* be the way to go..

**Comment by sleewoo** [comment]
> Can I ask what you need the union types for if you have the enums?

just compare:

```ts
where({ status: "pending" })
```

to

```ts
where({ status: ItemStatusEnum.pending })
```

why would i constantly import `ItemStatusEnum`  if i can use a string and it's automatically validated

![Screenshot_20230126_155740](https://user-images.githubusercontent.com/74734701/214854176-90a4ccb8-27a9-490d-a864-fd87767b8208.png)

**Comment by kristiandupont** [comment]
Oh, I thought you were showing me that example as why you wanted enums :-D So you need the enum in some other place?

**Comment by sleewoo** [comment]
vs

![Screenshot_20230126_160036](https://user-images.githubusercontent.com/74734701/214854819-687f339e-75ba-4990-8824-5fca3308c644.png)

what for all this fuss with importing enums if strings can be used

**Comment by sleewoo** [comment]
sure, i need enums on client, in Vue components

**Comment by sleewoo** [comment]
and unions in knex queries

**Comment by sleewoo** [comment]
sure i can write a customized hook, but so will have to do all who use this pattern - types in queries, enums on client.

**Comment by kristiandupont** [comment]
Right, I think I finally understand your situation. I can see the use case, though I do wonder how common it is. It seems related to #310 as well, and maybe I need to think of a more generic way to generate enum types that can satisfy various requirements.. 

I think for now that I would encourage you to write a custom hook because creating enums always, per default, doesn't feel like the right solution to me. I can try and help you get started if you want.

**Comment by sleewoo** [comment]
got it, makes sense, thanks.
