### ISSUE TITLE
Invalid value for option 'database' - expected type string, received value: postgresql://localhost:5432/acme

### ISSUE THREAD

**Issue by mike-hogan** [kristiandupont/kanel#375]
Run `npx kanel -d postgresql://localhost:5432/acme -o ./src/models` as per the docs, and I get 

`Invalid value for option 'database' - expected type string, received value: postgresql://localhost:5432/acme`

I am using Kanel 3.2.0

**Comment by kristiandupont** [comment]
Argh, that's embarrassing! I don't really have any tests for the CLI so these bugs tend to sneak in. I will look into it!

**Comment by kristiandupont** [comment]
Sorry about the delay. This should be fixed now.
