### ISSUE TITLE
Any way to generate Typescript `.d.ts` declaration files instead of `.ts`?

### ISSUE THREAD

**Issue by sepsol** [kristiandupont/kanel#379]
Thanks in advance!

**Comment by kristiandupont** [comment]
I guess not with the current setup, no. Can I ask a bit about the use case? Why is this necessary? Are you using any enums?

**Comment by sepsol** [comment]
One of the use cases is that it allows the type definitions to be used in purely `js` modules. Plus, it semantically makes sense to have all the type definitions of a project in type declaration (`.d.ts`) files.

**Comment by kristiandupont** [comment]
Yeah, I can see how that makes sense. What would you suggest in the case of enums? Should they be disallowed with this option?

**Comment by sepsol** [comment]
That's a good point. Honestly I don't have enough information on this but maybe [this](https://lukasbehal.com/2017-05-22-enums-in-declaration-files/) could be a solution.

**Comment by karloluis** [comment]
`|` chaining for Enums is what I've seen done in other tooling like the graphql "[codegen](https://the-guild.dev/graphql/codegen)".

**Comment by kristiandupont** [comment]
@karloluis I am not sure I follow. How do you use the pipe operator with enums?

**Comment by kristiandupont** [comment]
Ah right. That's possible by setting `enumStyle` to `type` for unions. I was considering making this the default as I greatly prefer unions over enums, but enums have the one upside that items can have comments.

**Comment by alecmev** [comment]
For future readers, you might not need this, TypeScript appears to be happy with packages that just do `"types": "./dist/index.ts"`, `index.ts` being generated by `generateIndexFile` pre-render hook.
