### ISSUE TITLE
Type issues

### ISSUE THREAD

**Issue by dmoose** [kristiandupont/kanel#4]
Cool, project.  Ran it against a schema I had and saw two issues both seem to be because of assumptions about postgres types.

The tables that used uuid for id do not seem to create Id values that are exported correctly.

Example:

import { ConfigsId } from './configs';

import DeviceType from './device-type';
import ConfigType from './config-type';

export type ConfigsId = number & { __flavor?: 'configs' };

export default interface Configs  {
  /**
   * Primary key. Index: configs_pkey
   * Index: idx_configs_on_config_UUID
  */
  uuid: ConfigsId;

Also ran into some postgres type issues.  Types like Uuid, Macaddr, Geography, etc are extracted but they are not defined.  Since Geography is from an extension it probably makes sense to add configuration that allows types to be defined and included into the generated files to handle the more unusual postgres types.

**Comment by dmoose** [comment]
Just read your comment to issue 3.  That looks like it would work to fix the additional types like Macaddr etc.  Just define them one level up and add a comment.  A little extra work making sure the comments are where they need to be.  The assumption about id being a number looks a little harder to work around.

**Comment by kristiandupont** [comment]
Ah yes, this is a symptom of the fact that I just extracted the code from a larger project, so these are cases that aren't covered yet. I think maybe type-comments would help but for this case, it seems more like you should be able to specify type mappings in the configuration file. I will look into that today.

ID's being hardcoded as numbers is a clear bug, they should extract the type of the column obviously. And yes, that might be slightly more difficult to fix but I will dig into that as well :-)

**Comment by kristiandupont** [comment]
I've just published a new version that fixes the id-type bug.

As for custom type mappings, it turns out that I had already implemented it, just not documented it yet. You can specify custom types in the `customTypeMap` config property. Note that it doesn't add import statements yet, so it will only work with primitives. It should probably be expanded.
