### ISSUE TITLE
kanel-kysely?

### ISSUE THREAD

**Issue by thelinuxlich** [kristiandupont/kanel#428]
I think this project could be the defacto schema generator for Kysely!

**Comment by kristiandupont** [comment]
Heh, it's been brought up [before](https://github.com/kristiandupont/kanel/issues/273). I am still using Knex even though I am starting to feel that it might be a bit dated. There seem to be a number of new alternatives popping up these days.

Do you use Kysely?

**Comment by thelinuxlich** [comment]
Heavily, if you are interested in using it I can help you too

**Comment by thelinuxlich** [comment]
Most people using Kysely also use this project to generate the schema: https://github.com/RobinBlomberg/kysely-codegen but it has a lot of limitations and Kanel seems much more complete.

**Comment by kristiandupont** [comment]
Cool, I'll keep that in mind! And obviously I am happy to accept PR's but I will also see if I can look into it at some point.
I am mostly focusing on seed generation at the moment. Does Kysely have any support for that?

**Comment by thelinuxlich** [comment]
It has a migration API but no CLI, ppl use this one https://github.com/acro5piano/kysely-migration-cli

I prefer graphile-migrate

**Comment by kristiandupont** [comment]
Right, so I guess seed data can be part of a migration, but I was actually thinking in terms of test data. But good to know, thanks! I wasn't aware of graphile-migrate, even though I use graphile-worker! :-D

**Comment by thelinuxlich** [comment]
I love it! It has a config for a seed file.

**Comment by kristiandupont** [comment]
So, looking at the getting started section of Kysely, it looks like the basics should be fairly trivial to get running. Two questions:

1) do you have a setup where you can test it out? I can set up a minimalistic environment but I am not going to do any advanced stuff

2) Does Kysely support branded types for id's? I am guessing it will just work but I would love to hear if you have experience with it. I consider that to be one of the defining features of Kanel as it has helped me a lot personally..

**Comment by thelinuxlich** [comment]
Anything we define as column type in the schema passed to Kysely, it will take as the source of truth.

For example, this is what kysely-codegen generates for json columns:
```ts
import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
	? ColumnType<S, I | undefined, U>
	: ColumnType<T, T | undefined, T>;

export type Int8 = ColumnType<string, string | number | bigint, string | number | bigint>;

export type Json = ColumnType<JsonValue, string, string>;

export type JsonArray = JsonValue[];

export type JsonObject = {
	[K in string]?: JsonValue;
};

export type JsonPrimitive = boolean | null | number | string;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;
```

ColumnType is probably the way because you may want different types depending on the operation(select, insert, update)

**Comment by thelinuxlich** [comment]
About testing, sure, I can provide a test suite with db tables containing json columns, timestamps, custom types etc

**Comment by kristiandupont** [comment]
So, I can see that you combine the types into a `Database` type in the examples. Should that *actually* cover the entire database, or would you create one per schema? The latter seems more likely to work to me, as naming collisions won't be a problem but maybe that would not be suited for other reasons?

**Comment by thelinuxlich** [comment]
Yeah, usually we add all table interfaces into a Database type so we don't need to manually refer to them when doing queries(so while it's possible to create one per table schema it's more fiddly for DX)

**Comment by kristiandupont** [comment]
Got it

**Comment by kristiandupont** [comment]
I guess I could just create types for the schemas and let `Database` be the union type of those. Then it will be quite easy to iterate from there if necessary..

**Comment by kristiandupont** [comment]
v0.0.1 of [kanel-kysely](https://www.npmjs.com/package/kanel-kysely) is up. This was obviously quickly hacked together so it won't work well with other extensions. But I would love for you to try it out!

**Comment by thelinuxlich** [comment]
Thanks, I'll fork and add some changes

**Comment by thelinuxlich** [comment]
Is this the best way to skip a branded id ?

```ts
![image](https://github.com/kristiandupont/kanel/assets/5043/6bff5e96-90f1-4da7-9074-bc0093797cb3)
```

**Comment by kristiandupont** [comment]
Yeah, that might be it. I guess I should change it so you could just give it `undefined` for `gerenrateIdentifierType` if you are not interested in it. Did the branded types break Kysely?

**Comment by thelinuxlich** [comment]
it won't break but although useful is a bit niche, not everybody knows about them or wants to use them.
