### ISSUE TITLE
How to handle JSON/JSONB columns?

### ISSUE THREAD

**Issue by thelinuxlich** [kristiandupont/kanel#429]
How do I enforce a specific type for a JSON column(like a sub-schema)?

**Comment by kristiandupont** [comment]
You can specify the type using a column comment. So if you have a table `user` with a column `address` that is JSON(B), you can run

```sql
COMMENT ON COLUMN user.address IS '@type:string ..and the rest of your comment, if any';
```

and now Kanel should turn it into a string. If you want to specify a type that needs to be imported, you can use `@type(MyType, 'my-library', false, true, false)`

The parameters are: name, path, isAbsolute, isDefault, importAsType

Yes, I need to document this :-)

**Comment by thelinuxlich** [comment]
hmmm interesting

**Comment by thelinuxlich** [comment]
Any reason why you opted for column comment instead of something like typeMap configuration?

**Comment by kristiandupont** [comment]
"Database as the source of truth", mostly. You can specify a type map but that will just allow you to specify *one* type for every JSON column, which is probably not what you want.

**Comment by karlhorky** [comment]
For anyone interested, also check out the similar challenges that [SafeQL](https://github.com/ts-safeql/safeql) by @Newbie012 faces:

- https://github.com/ts-safeql/safeql/issues/102
- https://github.com/ts-safeql/safeql/issues/179

**Comment by jcyh0120** [comment]
Is this still the suggested way to handle JSONB type with custom type definition? I saw some updates in v3 and a preRenderHook looks like a way to tweak custom column JSON types.

> You can specify the type using a column comment. So if you have a table `user` with a column `address` that is JSON(B), you can run
> 
> ```sql
> COMMENT ON COLUMN user.address IS '@type:string ..and the rest of your comment, if any';
> ```
> 
> and now Kanel should turn it into a string. If you want to specify a type that needs to be imported, you can use `@type(MyType, 'my-library', false, true, false)`
> 
> The parameters are: name, path, isAbsolute, isDefault, importAsType
> 
> Yes, I need to document this :-)

**Comment by kristiandupont** [comment]
Sorry no, I haven't written any documentation about it. The comment above is the closest thing to it. If it doesn't explain enough, try and tell me what type you need and I will write the corresponding comment for you :-)

**Comment by setvik** [comment]
What would the comment be for a jsonb field containing values of the following type:

```
{
  property1: string[];
  property2: string[];
  property3: number;
}
```

**Comment by kristiandupont** [comment]
Hm, the most obvious way at the moment is to create and export that type from somewhere. 

So, if in some folder that isn't deleted by Kanel when generating models, you define:

```ts
// src/types/AccountDetails.ts

export type AccountDetails = { name: string; balance: number };
```

You could add the following comment to your column:
`@type(AccountDetails, '../types/AccountDetails', false, false, true)`

That is assuming Kanel targets a folder under `src` like `src/models`, which will make the relative path correct.

This is all off the top of my head, so I might be getting something wrong. Let me know if it doesn't seem to work!

**Comment by dil-dvukman** [comment]
I'm trying to use @type but I can't figure it out

Column comment:
`@type:(Configuration, 'common-types/configuration', true, false, true)`

but all I get is a comment above the field, it doesn't import the package and not change the type:
```
  /** :(Configuration, 'common-types/configuration', true, false, true) */
  configuration?: unknown;
```

Is it a bug or I missed something?

**Comment by kristiandupont** [comment]
The syntax is confusing, I agree. I think the problem there is that the colon is superfluous. Either you use a colon, *or* you use parenthesis (as if it's a function being applied). And yes, I need to document this.

**Comment by ersinakinci** [comment]
Does the syntax not support defining complex types inline? I tried

```sql
comment on column "scenario"."data" is '@type:{percentageBusinessUsage?:number;homeId?:string;businessEntityId?:string;startDate?:string;}'
```

with and without spacing, colon vs. parentheses, etc., and all I get is the comment generated similar to @dil-dvukman.

**Comment by ersinakinci** [comment]
Ah, I see that it doesn't, I will have to import for anything other than `string`:

https://github.com/kristiandupont/kanel/blob/0bc849114d44b64b4a22fb8bd4029cd55496adfc/packages/kanel/src/generators/resolveType.ts#L23-L46

**Comment by WMcKibbin** [comment]
dropping this here for other internet travelers
```sql
-- path, isAbsolute, isDefault, importAsType
COMMENT ON COLUMN locations.address IS E'@type(Address, \'../non-generated/Address\', true, false, true)';
```
This will output
```ts
import type { Address } from '../non-generated/Address';
...

export default interface ManufacturerLocationsTable {
  id: ColumnType<ManufacturerLocationsId, ManufacturerLocationsId, ManufacturerLocationsId>;

  manufacturerId: ColumnType<ManufacturersId | null, ManufacturersId | null, ManufacturersId | null>;

  name: ColumnType<string | null, string | null, string | null>;

  address: ColumnType<Address | null, Address | null, Address | null>;
}
```

Yet to figure out how to properly populate properly this when I query but Ill get there im sure.

**Comment by Kilowhisky** [comment]
> Yeah, interestingly I was struggling with this myself yesterday. I have a generic type that requires two imports which is not possible with the current syntax.
> 
> The solution I am going with is to move that information out of the database, even though it conflicts with my "Postgres as the source of truth" principle. But basically, I created a new pre-render hook that will replace specific types. So, I am now specifying a few `table.column` types in the Kanel configuration file instead. It's quite a bit easier to work with. It's scrappy so far, but I might polish it a bit and include it as a built-in hook..
> 
> If you are interested, this is what it currently looks like:
> 
> ```js
> /** @type {import("kanel").PreRenderHook} */
> const specificTypes = async (outputAcc, instantiatedConfig) => {
>   const mappings = {
>     "OauthConnection.encrypted_tokens": {
>       name: "EncryptedJSON<OauthTokens>",
>       typeImports: [
>         {
>           name: "EncryptedJSON",
>           path: "./src/util/EncryptedJSON",
>           isDefault: false,
>           isAbsolute: false,
>           importAsType: true,
>         },
>         {
>           name: "OauthTokens",
>           path: "./src/oauth/oauthTokens",
>           isDefault: false,
>           isAbsolute: false,
>           importAsType: true,
>         },
>       ],
>     },
>   };
> 
>   const output = { ...outputAcc };
> 
>   for (const path of Object.keys(output)) {
>     const file = outputAcc[path];
>     const declarations = file.declarations.map((decl) => {
>       const declaration = { ...decl };
> 
>       if (declaration.declarationType === "interface") {
>         for (const field of declaration.properties) {
>           const key = `${declaration.name}.${field.name}`;
>           if (mappings[key]) {
>             field.typeName = mappings[key].name;
>             declaration.typeImports = [
>               ...(declaration.typeImports || []),
>               ...mappings[key].typeImports,
>             ];
>           }
>         }
>       }
>       return declaration;
>     });
> 
>     output[path] = {
>       ...file,
>       declarations,
>     };
>   }
> 
>   return output;
> };
> ```

I know this is old but i vote for this. I *absolutely* do not want to have the DB reference code somewhere. That seems like a complete reversal of information flow.  The syntax also is just ugly as sin.

**Comment by Kilowhisky** [comment]
Here's a completely crazy idea. 

How about the syntax: 

```
customTypeMap: {
   'jsonb@myschema.mytable':  { name: 'myJsonType', typeImports: [{ name: 'myJsonType', path: 'mylib', isAbsolute: true }] }
}
```

It could easily be added here: 
https://github.com/kristiandupont/kanel/blob/60aabfdb08b42e961c91fda64bcd5002bd099d4f/packages/kanel/src/generators/resolveType.ts#L235-L238

as 
```
  // 5.1) If there is a typemap type specific to this table, use that
  if (`${c.type.fullName}@${c.table.fullName}` in config.typeMap) {
    return config.typeMap[${c.type.fullName}@${c.table.fullName}];
  }
```
I'm making a wild assumption about `c.table.fullName` but it feels like this is available somewhere.

**Comment by kristiandupont** [comment]
That could work but is it really much better to have the information in the config file? It seems to me that at that point, a hook is the same level removed from the database. I have thought about expanding the syntax in the comments to allow multiple imports, but it also gets tedious to encode into comments.

**Comment by Kilowhisky** [comment]
I think it's way better. 

Db comments were never meant to hold code. They can't be linted, checked or anything like that. Other systems may also use it. So you are really taking ownership of a shared resource that wasn't designed for it. 

The config file can do all of that and is also co-located with the code (usually). It's just much closer to its area of concern. Also, you own the file and its spec. 

In truth I'd prefer that json columns get an auto generated type that could that can be defined or overridden. But unfortunately typescript isn't setup to allow interface/class partials like C# and Java. So I can't just write a static file and having it auto mixed with the base implementation. 

As for the syntax it could be. 

`Schema.type@schema.table[.column]`

**Comment by thelinuxlich** [comment]
I'm willing to sacrifice these benefits to have DB as the source of truth. I did something similar to kanel on my setup with mysql

**Comment by Kilowhisky** [comment]
If you really want DB as source of truth you can check for existence of this extension and pull the schema from it. 

https://github.com/gavinwahl/postgres-json-schema

**Comment by Kilowhisky** [comment]
Or this which is supposedly 20x faster

**Comment by Kilowhisky** [comment]
I guess overall I'd vastly prefer using JSON Schema to infer typescript type than some one-off syntax.

**Comment by kristiandupont** [comment]
@Kilowhisky I get why you prefer editing text in the repo over database comments. My question was why it's preferable to have it in the config file over a hook. If I was to redesign things, I would have even less logic in the "core", because it's already more complicated than I like. Hooks can reside in the same folder and allow as much or little custom logic as you like. The only problem is that they don't compose well.

I am considering making the hook that I use public and streamline it a bit. I think it covers most cases nicely.

**Comment by Kilowhisky** [comment]
I wouldn't say its preferrable. Just an alternative i thought was cleaner and easier to implement. It hadn't come up, so i mentioned it.

**Comment by Kilowhisky** [comment]
I made the example hook more generic. The only problem i see is that they don't take into account two tables with the same name but different schemas. 

```
const { makeKyselyHook } = require("kanel-kysely");

/**
 * Allows for injection of custom types from the mapping of `table.field`
 * @param {import("kanel").TypeMap} mappings 
 * @returns {import("kanel").PreRenderHook}
 */
const specificTypes = (mappings) => {
  /** @type {import("kanel").PreRenderHook} */
  return async (outputAcc, instantiatedConfig) => {
    const output = { ...outputAcc };

    for (const path of Object.keys(output)) {
      const file = outputAcc[path];
      const declarations = file.declarations.map((decl) => {
        const declaration = { ...decl };

        if (declaration.declarationType === "interface") {
          for (const field of declaration.properties) {
            const key = `${declaration.name}.${field.name}`;
            if (mappings[key]) {
              field.typeName = mappings[key].name;
              declaration.typeImports = [
                ...(declaration.typeImports || []),
                ...mappings[key].typeImports,
              ];
            }
          }
        }
        return declaration;
      });

      output[path] = {
        ...file,
        declarations,
      };
    }

    return output;
  };
}

/** @type {import('kanel').Config} */
module.exports = {
  connection: {
    host: 'localhost',
    user: 'postgres',
    password: 'postgres',
    database: 'postgres',
    port: 54322,
  },
  schemas: ['log', 'geo'],
  preDeleteOutputFolder: true,
  outputPath: './src/database/schema',
  preRenderHooks: [
    specificTypes({
      'Places.props': {
        name: 'PlaceProps',
        typeImports: [{
          name: 'PlaceProps',
          path: "./src/database/models/PlaceProps",
          isDefault: false,
          isAbsolute: false,
          importAsType: true,
        }]
      }
    }),
    makeKyselyHook({
      includeSchemaNameInTableName: true
    })
  ],
  customTypeMap: {
    'extensions.geometry': { name: 'Geometry', typeImports: [{ name: 'Geometry', path: 'geojson', isAbsolute: true }] },
  }
}
```
