### ISSUE TITLE
kanel-kysely provide a way to configure declaration name affixes.

### ISSUE THREAD

**Issue by virtuallyunknown** [kristiandupont/kanel#437]
To explain the issue simply, I am really not a fan of this naming system:

```ts
export type Countries = Selectable<CountriesTable>;
export type NewCountries = Insertable<CountriesTable>;
export type CountriesUpdate = Updateable<CountriesTable>;
```

**New**Countries and Countries**Update**. These affixes seem to be hard-coded by the `kanel-kysely` plugin. 

https://github.com/kristiandupont/kanel/blob/main/packages/kanel-kysely/src/processFile.ts#L144
https://github.com/kristiandupont/kanel/blob/main/packages/kanel-kysely/src/processFile.ts#L162

It would be really nice if `makeKyselyHook` accepted an option to configure how these declaration names are constructed or there was some other way to modify them. I tried using the `getMetadata` function of `processDatabase` along with the `makeKyselyHook` plugin, but that doesn't work probably because `getMetadata` is called before the plugin, so there isn't much you can do about this.

**Comment by thelinuxlich** [comment]
Agreed, I think the only way rn is on postRenderHooks

**Comment by virtuallyunknown** [comment]
> Agreed, I think the only way rn is on postRenderHooks

I think so too, but even the docs mention that this is a brute-force approach and it should be more like a last resort method.

**Comment by kristiandupont** [comment]
I've just published a new version where this is configurable. You can now do something like this:

```js
const getKyselyItemMetadata = (d, selectorName, canInitialize, canMutate) => ({
  tableInterfaceName: `TableFor${selectorName}`,
  selectableName: selectorName + 'Selectable',
  insertableName: canInitialize ? `${selectorName}Insertable` : undefined,
  updatableName: canMutate ? `${selectorName}Updateable` : undefined,
})
```

..and then, in .kanelrc.js:

```
preRenderHooks: [makeKyselyHook({ getKyselyItemMetadata })]
```

**Comment by thelinuxlich** [comment]
So I think we can close this one

**Comment by virtuallyunknown** [comment]
> I've just published a new version where this is configurable. You can now do something like this:
> 
> ```js
> const getKyselyItemMetadata = (d, selectorName, canInitialize, canMutate) => ({
>   tableInterfaceName: `TableFor${selectorName}`,
>   selectableName: selectorName + 'Selectable',
>   insertableName: canInitialize ? `${selectorName}Insertable` : undefined,
>   updatableName: canMutate ? `${selectorName}Updateable` : undefined,
> })
> ```
> 
> ..and then, in .kanelrc.js:
> 
> ```
> preRenderHooks: [makeKyselyHook({ getKyselyItemMetadata })]
> ```

Thanks a lot Kristian, appreciate it :clap: 

If I understand correctly, this is similar to `processDatabase.getMetadata` but it is specific for the kysely plugin? Really nice.

I was also going to ask if it's possible to modify the output path so that the files are not emitted under a `schemaName` directory, but I was able to do that with the `getMetaData` function itself!

```js
getMetadata: (details, generateFor, instantiatedConfig) => {
    const isAgentNoun = ['selector', 'initializer', 'mutator'].includes(generateFor) && details.kind !== 'enum';
    // const suffix = isAgentNoun ? `_${generateFor}` : '';

    const relationComment = isAgentNoun
        ? `Represents the ${generateFor} for the ${details.kind} ${details.schemaName}.${details.name}`
        : `Represents the ${details.kind} ${details.schemaName}.${details.name}`;

    return {
        name: toPascalCase(details.name),
        comment: [relationComment],
        path: join(instantiatedConfig.outputPath, toPascalCase(details.name)),
    };
},
```

**Comment by kristiandupont** [comment]
Great! Yes, it's the same approach. We can expand it with optional comments and possibly other things from here, I wanted you to try it out before even documenting it.

**Comment by virtuallyunknown** [comment]
> Great! Yes, it's the same approach. We can expand it with optional comments and possibly other things from here, I wanted you to try it out before even documenting it.

Hey again. So actually I was just testing things out as we speak, and I stumbled upon a problem, the example I gave from above is actually incorrect in what I am trying to achieve. My bad for not thoroughly testing it before replying.

But let's say I want to change the path to where the types are emitted, here is a bare-minimum `getMetadata` function which only modifies the `path`, and the thought process is that we will let `makeKyselyHook` + `getKyselyItemMetadata` handle affixes for us, since it runs **after** `getMetadata` right?

```js
import { join } from 'node:path'
import kanel from 'kanel';
import { recase } from '@kristiandupont/recase';
import { generateIndexFile } from './generate-index-file.js';
import { trimWhitespace } from './trim-whitespace.js';
import kanelKysely from 'kanel-kysely';

const toPascalCase = recase('snake', 'pascal');

const getKyselyItemMetadata = (d, selectorName, canInitialize, canMutate) => {
    return ({
        tableInterfaceName: `DB${selectorName}`,
        selectableName: `DB${selectorName}Selectable`,
        insertableName: canInitialize ? `DB${selectorName}Insertable` : undefined,
        updatableName: canMutate ? `DB${selectorName}Updateable` : undefined,
    });
}

export async function processDatabase() {
    await kanel.processDatabase({
        connection: {
            // credentials
        },

        outputPath: 'src/types',
        resolveViews: true,
        preDeleteOutputFolder: true,
        enumStyle: 'type',

        preRenderHooks: [generateIndexFile, kanelKysely.makeKyselyHook({ getKyselyItemMetadata })],
        postRenderHooks: [trimWhitespace],

        getMetadata: (details, generateFor, instantiatedConfig) => {
            return {
                name: toPascalCase(details.name),
                comment: [`generateFor: ${generateFor} | details.name: ${details.name} | details.kind: ${details.kind}`],
                path: join(instantiatedConfig.outputPath, toPascalCase(details.name)),
            };
        },
    });
}

await processDatabase();
```

The kysely hook part works as intended, however, any time the `getMetadata` function is present, it will emit it's types no matter what, so this is what ended up generating:

```ts
import type { ColumnType, Selectable, Insertable, Updateable } from 'kysely';

/** Identifier type for public.countries */
export type CountriesId = number & { __brand: 'CountriesId' };

/** generateFor: selector | details.name: countries | details.kind: table */
export default interface DBCountries {
  id: ColumnType<CountriesId, CountriesId, CountriesId | null>;
  name: ColumnType<string, string, string | null>;
}

/** generateFor: initializer | details.name: countries | details.kind: table */
export interface DBCountries {
  id: ColumnType<CountriesId, CountriesId, CountriesId | null>;
  name: ColumnType<string, string, string | null>;
}

/** generateFor: mutator | details.name: countries | details.kind: table */
export interface DBCountries {
  id?: ColumnType<CountriesId, CountriesId, CountriesId | null>;
  name?: ColumnType<string, string, string | null>;
}

export type DBCountriesSelectable = Selectable<DBCountries>;

export type DBCountriesInsertable = Insertable<DBCountries>;

export type DBCountriesUpdateable = Updateable<DBCountries>;
```

So now you have two unnecessary `DBCountries` types, one for an `initializer` and for `mutator`, where we only needed a single one for the `selector`.

Is there any way around this problem, or it needs some options needs to be exposed to `getKyselyItemMetadata` in order to control this?

**Comment by kristiandupont** [comment]
Right, so the issue here is that the kysely hook works in a quirky way. The regular Kanel will always attempt to output one or three interfaces: a selector, an initializer and a mutator. The Kysely hook works by transforming the selector and filtering out the two others, only to then create another one or three interfaces for the Kysely Selectable, etc. ones.

So, with the `getMetadata`  function you have there, selectors, initializers and mutators will all be named identically. This confuses the Kysely hook. Try changing your `getMetadata` to something like:

```js
        getMetadata: (details, generateFor, instantiatedConfig) => {
            return {
                name: toPascalCase(details.name) + generateFor,
                comment: [`generateFor: ${generateFor} | details.name: ${details.name} | details.kind: ${details.kind}`],
                path: join(instantiatedConfig.outputPath, toPascalCase(details.name)),
            };
        },
```

**Comment by kristiandupont** [comment]
(And yes, this is confusing. It would take a bit of an architectural rewrite to allow for a more intuitive configuration scheme, so I am not going to be doing that just yet. There seems to be quite a few libraries popping up in this space at the moment, so I'll keep an eye on where things move and possibly change things around again)

**Comment by virtuallyunknown** [comment]
> Right, so the issue here is that the kysely hook works in a quirky way. The regular Kanel will always attempt to output one or three interfaces: a selector, an initializer and a mutator. The Kysely hook works by transforming the selector and filtering out the two others, only to then create another one or three interfaces for the Kysely Selectable, etc. ones.
> 
> So, with the `getMetadata` function you have there, selectors, initializers and mutators will all be named identically. This confuses the Kysely hook. Try changing your `getMetadata` to something like:
> 
> ```js
>         getMetadata: (details, generateFor, instantiatedConfig) => {
>             return {
>                 name: toPascalCase(details.name) + generateFor,
>                 comment: [`generateFor: ${generateFor} | details.name: ${details.name} | details.kind: ${details.kind}`],
>                 path: join(instantiatedConfig.outputPath, toPascalCase(details.name)),
>             };
>         },
> ```

Okay, your explanation makes sense. The kysely hook somehow relies on `details.name` to figure out what is `selectable`, `insertable` or `mutatable`? Something like that?

There was one downside, in that the names generated were like this:

```ts
import type { ColumnType, Selectable, Insertable, Updateable } from 'kysely';

/** Identifier type for public.countries */
export type CountriesId = number & { __brand: 'CountriesId' };

/** generateFor: selector | details.name: countries | details.kind: table */
export default interface DBCountriesSelector {
  id: ColumnType<CountriesId, CountriesId, CountriesId | null>;
  name: ColumnType<string, string, string | null>;
}

export type DBCountriesSelectorSelectable = Selectable<DBCountriesSelector>;
export type DBCountriesSelectorInsertable = Insertable<DBCountriesSelector>;
export type DBCountriesSelectorUpdateable = Updateable<DBCountriesSelector>;
```

Like, `DBCountriesSelectorSelectable`, doesn't make any sense. Either way, I managed to solve this by modifying the kysely hook with a regular expression, which in my opinion is still an okay solution.

```js
const getKyselyItemMetadata = (d, selectorName, canInitialize, canMutate) => {
    const selector = selectorName.replace(/selector$/i, '')
    return ({
        tableInterfaceName: `DB${selector}`,
        selectableName: `DB${selector}Selectable`,
        insertableName: canInitialize ? `DB${selector}Insertable` : undefined,
        updatableName: canMutate ? `DB${selector}Updateable` : undefined,
    });
}
```

Thanks for helping me out. I am going to spend some time migrating from kysely-codegen to kanel and in case I notice anything else will let you know. Cheers!

**Comment by kristiandupont** [comment]
Ah, right. Yes, the `selectorName` is the name that the "outer" Kanel machinery came up with using the regular configuration. The `d` parameter has all the details (table name, etc.), if you want to extract it from there. Another alternative would be to do something closer to the default config:

```js
        getMetadata: (details, generateFor, instantiatedConfig) => {
            return {
                name: toPascalCase(details.name) + (generateFor === 'selector' ? '' : generateFor),
                comment: [`generateFor: ${generateFor} | details.name: ${details.name} | details.kind: ${details.kind}`],
                path: join(instantiatedConfig.outputPath, toPascalCase(details.name)),
            };
        },
```

This will make the selector simply be the pascal-cased table name.

**Comment by virtuallyunknown** [comment]
> Ah, right. Yes, the `selectorName` is the name that the "outer" Kanel machinery came up with using the regular configuration. The `d` parameter has all the details (table name, etc.), if you want to extract it from there. 

Oh nice, it didn't occur to me I could do that. Really nice since I don't have to rely on regex anymore, can basically construct the names and affixes from `d.name`.

```js
const toPascalCase = recase('snake', 'pascal');

function getKyselyItemMetadata(d, selectorName, canInitialize, canMutate) {
    const tableName = toPascalCase(d.name);
    return ({
        tableInterfaceName: `DB${tableName}`,
        selectableName: `DB${tableName}Selectable`,
        insertableName: canInitialize ? `DB${tableName}Insertable` : undefined,
        updatableName: canMutate ? `DB${tableName}Updatablee` : undefined,
    })
}
```

The only things left to complete my migration now would be the ESM post-render hook and the `generateIndexFile`, hopefully I won't run into issues there.

Cheers!

**Comment by kristiandupont** [comment]
Awesome!
Yes, the whole ESM transition is in front of me as well, I've been procrastinating on it in [Schemalint](https://github.com/kristiandupont/schemalint/issues/264) as well. Let me know what you learn along the way!

**Comment by virtuallyunknown** [comment]
> Awesome! Yes, the whole ESM transition is in front of me as well, I've been procrastinating on it in [Schemalint](https://github.com/kristiandupont/schemalint/issues/264) as well. Let me know what you learn along the way!

Okay so basically I spent the whole day working on this, and there is a lot to unpack but I think I managed to get everything working in the state I want it to be, with some exceptions.

Here is my repository - https://github.com/virtuallyunknown/kanel-kysely-custom, you can clone and test if you like.

**First**, I wanted every possible type declaration emitted by Kanel - `table`, `view`, `materializedView`, `compositeType`, `domain`, `enum`, `range` as well as `identifier` types to be prefixed with `DB`. In the process, I learned that:

- `table` kinds should also have `selectable`, `insertable` and `updatable` types.
- `view`, `materializedView` and `compositeType` kinds should have `selectable` type.
- `domain`, `enum`, `range` should only have a simple interface.

In order to maintain naming consistency across all functions and hooks, I had to delegate the task of creating type names to a custom function (named `generateTypeNames`) that I made for this purpose:

```
import { toPascalCase } from './recase.js';

export function generateTypeNames({ name, isTable }) {
    const pascalName = toPascalCase(name);

    return isTable
        ? {
            tableInterfaceName: `DB${pascalName}`,
            selectableName: `DB${pascalName}Selectable`,
            insertableName: `DB${pascalName}Insertable`,
            updatableName: `DB${pascalName}Updateable`
        }
        : { name: `DB${pascalName}` }
}
```

https://github.com/virtuallyunknown/kanel-kysely-custom/blob/master/kanel/util/generate-type-names.js

I use this function in multiple places.

- [In the `processDatabase.generateIdentifierType` function.](https://github.com/virtuallyunknown/kanel-kysely-custom/blob/master/kanel/process.js#L60)
- [In the `processDatabase.getMetadata` function](https://github.com/virtuallyunknown/kanel-kysely-custom/blob/master/kanel/process.js#L46) where `details.kind` is **not** a `table`, since you told me that breaks internal library logic, besides the kysely plugin deals with this.
- [In several places in my `generateIndexHook`](https://github.com/virtuallyunknown/kanel-kysely-custom/blob/master/kanel/hooks/generate-index.js#L28-L64).

**Second**, I wanted to create a hook that generates an index file, and figuring out how that works too me quite a while as well. As mentioned above, tables need interface + types for `selectable`, `insertable` and `updatable`. Views, materialized views and composite types need interface + `selectable` type. Lastly, `domain`, `enum`, `range` only need a single type, so I had to account for all of that, and use my little `generateTypeNames` function for that purpose, in order to match names and exports elsewhere.

The default `generateIndexFile` hook that [comes from the Kanel library](https://github.com/kristiandupont/kanel/blob/main/packages/kanel/src/hooks/generateIndexFile.ts#L35) is using `instantiatedConfig.getMetadata(...)` to generate type names, but those names obviously don't match my custom names, and I suspect this hook won't work with the kysely plugin out of the box.

Anyway, here is the end result of all this effort - my beautiful index file.

```ts
export type { default as DBMyDomain } from './db/MyDomain.js';
export type { default as DBMyEnum } from './db/MyEnum.js';
export type { default as DBMyRange } from './db/MyRange.js';
export type { default as DBBar, DBBarSelectable, DBBarInsertable, DBBarUpdateable, DBBarId } from './db/Bar.js';
export type { default as DBFoo, DBFooSelectable, DBFooInsertable, DBFooUpdateable, DBFooId } from './db/Foo.js';
export type { default as DBMyView, DBMyViewSelectable } from './db/MyView.js';
export type { default as DBMyMaterializedView, DBMyMaterializedViewSelectable } from './db/MyMaterializedView.js';
export type { default as DBMyComposite, DBMyCompositeSelectable } from './db/MyComposite.js';
```

https://github.com/virtuallyunknown/kanel-kysely-custom/blob/master/src/types/db-types.ts

This is very valuable for me, since in my real codebase I have data coming from an API, and data from a database. Having all of my database types prefixed with `DB` helps quite a lot. Additionally with `kysely-codegen` I had to manually create the `selectable`, `insertable` and `updateable` types, and it doesn't create types for materialized views. None of this is an issue anymore!

---

What I couldn't manage to do:

- Don't know how to modify the [`PublicSchema.ts`](https://github.com/virtuallyunknown/kanel-kysely-custom/blob/master/src/types/db/PublicSchema.ts) file in any way.
- `PublicSchema.ts` is using snake_case instead of PascalCase.
- Include `PublicSchema.ts` or [`db.ts`](https://github.com/virtuallyunknown/kanel-kysely-custom/blob/master/src/types/db.ts) in my index file.
---

What can be improved (in my opinion):

- An option to allow named exports for `table`, `composite`, `domain`, `enum`, and `range` kinds instead of default exports.
- I am very satisfied that I managed to make things work with my `generateTypeNames` function, however it feels like I'm rewriting internal library logic here, and it was a significant time investment. Things are also probably going to break with a future Kanel update.

---

Okay, that's about it. I hope you or someone else reading this later on finds this feedback and code examples useful.

Cheers.

**Comment by thelinuxlich** [comment]
It seems the only reason the generateIndex hook won't work with kanel-kysely is because the adapter skips the mutator generation?

**Comment by virtuallyunknown** [comment]
Okay, a big update here. Thanks to @thelinuxlich I was able to simplify the hook that generates the index by a significant margin. Instead of using `instantiatedConfig` to build the types, we're using `outputAcc`. Important to note that the order of the hooks which you pass to `preRenderHooks` is important, `generateIndexHook` must come **after** the kysely hook.

```js
import { join, relative, sep } from "path";
import { generateTypeNames } from '../util/generate-type-names.js';

export function generateIndexHook(outputAcc, instantiatedConfig) {
    debugger;

    const indexFile = {
        declarations: [
            {
                declarationType: "generic",
                lines: Object.entries(outputAcc).map(([key, value]) => {
                    const defaultExport = 'default as ' + value.declarations.find(declaration => declaration.exportAs === 'default').name;
                    const namedExports = value.declarations.flatMap(declaration => declaration.exportAs === 'named' ? declaration.name : []);
                    const importPath = sep === '\\'
                        ? relative(instantiatedConfig.outputPath, key).replace(/\\/g, "/")
                        : relative(instantiatedConfig.outputPath, key)

                    return `export type { ${[defaultExport, ...namedExports].join(', ')} } from './${importPath}';`
                }),
            },
        ],
    }

    const path = join(instantiatedConfig.outputPath, "db-types");

    return {
        ...outputAcc,
        [path]: indexFile,
    };
}
```

This hook also appears to work with the default configurations for kanel and kanel-kysely (without customizations).

**Comment by virtuallyunknown** [comment]
> Wow, nice work @virtuallyunknown, you are treading new ground so I appreciate the patience! :-)
> 
> > it feels like I'm rewriting internal library logic here
> 
> Yeah, this is a general problem with this sort of library. I was contemplating whether it was worth it or if it was better to create a new library based on [extract-pg-schema](https://github.com/kristiandupont/extract-pg-schema/), because that's almost where we are.
 
To be honest, the quote about rewriting library logic was only because it felt I needed a function to hold things in place so they don't fall apart (implying that it's the library itself should provide tools and logic for that, not the consumer), and I needed to reuse this function in multiple places, but all of that was before @thelinuxlich suggested the other solution to me.

As it stands currently, even with my heavily customized solution, I only need my custom naming function for the `processDatabase` config and not in the hooks anymore, or I can even opt out of using said function without it creating that big of a problem. For me personally this is totally in the realm of acceptable given how much I want to change and modify things around.

> It has been surprisingly difficult for me to come up with decent encapsulations/abstractions that give all the necessary flexibility that people might want but while still working well out of the box. A "type" means so many things, and there are very few ways to slice things that don't involve deal-breaking compromise. I am very open to suggestions for how to improve things.

Sorry if this is a cop-out answer, but the only suggestion I can give is as an end-consumer of the library, because I understand how difficult it is to put all of this together and make it work for thousands of people. So definitely don't want to risk giving bad advice.

I think [this part](https://github.com/kristiandupont/kanel/issues/437#issuecomment-1643307990) which you explained to me yesterday is the only thing that can be confusing, but other than that I'm not sure.

Proper ESM support would be really nice, and perhaps having some control over the [PublicSchema.ts](https://github.com/virtuallyunknown/kanel-kysely-custom/blob/master/src/types/db/PublicSchema.ts) would be nice, but that's not directly related to what you're asking here.

---

Btw, it was suggested to me I submit a PR with the hook, but when I clone Kanel and open the monorepo locally I get about 1 million eslint errors, and `Cannot find module 'kanel' or its corresponding type declarations` so I cant even run the build scripts, not really sure what's up with that. If you like the hook and think it's proper/production ready, feel free to include it, cause it might be easier this way.

Cheers.

**Comment by kristiandupont** [comment]
>I get about 1 million eslint errors

That's surprising, because CI [runs everything](https://github.com/kristiandupont/kanel/blob/main/.github/workflows/pull-requests.yml) without problems.. Which package manager did you use?

As for PublicSchema using snake_case, isn't the whole idea that the names match the table name and the value matches the Kysely corresponding type? I though if that was manipulated, Kysely wouldn't work, or did I misunderstand that?

**Comment by virtuallyunknown** [comment]
> That's surprising, because CI [runs everything](https://github.com/kristiandupont/kanel/blob/main/.github/workflows/pull-requests.yml) without problems.. Which package manager did you use?

NPM. Also, ignore the `eslint` part, I think that's an issue on my end sorry about that. But for whatever reason I am getting `Cannot find module 'kanel' or its corresponding type declarations.` all I do this:

```zsh
git clone https://github.com/kristiandupont/kanel.git
cd kanel
npm i
```

![image](https://github.com/kristiandupont/kanel/assets/24871108/525ef026-18b2-4e86-8cb1-009d07c5e3f3)

```zsh
npm run build --workspace=kanel-kysely
```

This command fails. No idea why that is, maybe I'm doing something wrong.

> As for PublicSchema using snake_case, isn't the whole idea that the names match the table name and the value matches the Kysely corresponding type? I though if that was manipulated, Kysely wouldn't work, or did I misunderstand that?

You are technically correct I think, but there is the so called [`CamelCasePlugin`](https://kysely-org.github.io/kysely/classes/CamelCasePlugin.html) (which I use), so if you have that enabled, the tables in your postgres database can be in snake_case, but the types that you pass to the Kysely instance can be (and should be) in camelCase.

So for example, it wouldn't be an issue at all if my `PublicSchema.ts` had camelCase keys. If you log the queries that Kysely actually sends to your database, it's still sending snake_case (original table names). It's freaking awesome.

```ts
await db.selectFrom('myView').selectAll().execute();
await db.selectFrom('myMaterializedView').selectAll().execute();
```
```zsh
kysely:query: select * from "my_view"
kysely:query: duration: 0.9ms
kysely:query: select * from "my_materialized_view"
kysely:query: duration: 0.2ms
```

**Comment by kristiandupont** [comment]
Okay, I'll look into the installation issue. And point taken regarding the naming. I guess that should be configurable as well then. Ah, config options! :-D

**Comment by virtuallyunknown** [comment]
> Okay, I'll look into the installation issue. And point taken regarding the naming. I guess that should be configurable as well then. Ah, config options! :-D

If you find the time, it would be lovely. Otherwise I think it might be possible to tweak this myself by modifying the `outputAcc` object. Just one question though, is the `name` property of the declaration always going to be the name of the schema + the world "schema", like `Public` + `Schema`.

![image](https://github.com/kristiandupont/kanel/assets/24871108/fa3e12f6-1cb5-4fb7-bc7d-a328deee885a)

**Comment by kristiandupont** [comment]
As it is currently, [yes](https://github.com/kristiandupont/kanel/blob/main/packages/kanel-kysely/src/makeKyselyHook.ts#L64). But that should probably be configurable as well. I guess that and the schema-property naming should be combined into a config object/callback..

**Comment by virtuallyunknown** [comment]
@kristiandupont sorry to bother again, but I accidentally found what was causing the `Cannot find module 'kanel' or its corresponding type declarations` error.

VSCode ships with it's own Typescript version which it's using by default. [But you can switch to instead the "workspace" version](https://code.visualstudio.com/docs/typescript/typescript-compiling#_using-the-workspace-version-of-typescript), or the one that is relevant to the current project and installed in `node_modules`.

That's what I did, and problem went away. You might consider creating a `.vscode/settings.json` with this setting pre-applied.

**Comment by thelinuxlich** [comment]
send PR :)

**Comment by virtuallyunknown** [comment]
> send PR :)

The issue might not even be related to VSCode itself. Try this:

```zsh
sudo npm i -g typescript@5.1.3
git clone https://github.com/kristiandupont/kanel.git
cd kanel
npm i
```

Leave the directory and run tsc from elsewhere:

```
tsc --project kanel/packages/kanel-kysely
```
