### ISSUE TITLE
Use optional field instead of null

### ISSUE THREAD

**Issue by louneskmt** [kristiandupont/kanel#439]
Internally (at the Postgres client level), I convert all `null` values to `undefined`. It is not uncommon to only handle `undefined` and completely drop `null`. I use some tricks to adapt the Kanel outputs to this scheme (i.e. converting all nullable properties to optional properties with no `null` union), but do you think it is something it would makes sense to support natively? Or is that too project-specific?

**Comment by kristiandupont** [comment]
Hm, I would say that I would like to hear from at least another person or two who does something similar. 

As is evident from the other issues, the configuration system is overwhelmingly complex as it is, so if you have a solution that works, maybe that's worth sticking with for now?
