### ISSUE TITLE
Cannot find name 'Numeric' / 'Double precision'

### ISSUE THREAD

**Issue by naftis** [kristiandupont/kanel#44]
```sql
CREATE TABLE test (
  samples DOUBLE PRECISION[] NOT NULL,
  more_samples NUMERIC[] NOT NULL
);
```
Generated types
```ts
export default interface Test {
  more_samples: Numeric[]; // Cannot find name 'Numeric'. ts(2304)
  samples: Double precision[]; // syntax error
}
```

Quick fix;  I've made `kanel.d.ts` where I've declared some of these types:
```ts
declare type Uuid = string;
declare type Interval = string;
declare type Numeric = number;
declare type Gender = "MALE" | "FEMALE" | "OTHER"; // enum type in my db
```
But with for example `double precision`, the type should be `DoublePrecision` or similar, because TypeScript doesn't allow a space in type name

**Comment by kristiandupont** [comment]
You should be able to work around this with a [custom type map](https://github.com/kristiandupont/kanel/blob/master/example/.kanelrc.js#L23) in your .kanelrc file:
```
customTypeMap: {
    'double precision[]': 'number[]',
    'numeric[]': 'string[]'
}
```
The map should probably not require the array qualifiers, I will fix that. But for now, this should work. 

Note also that JS numbers don't have sufficient precision for `NUMERIC` fields, so you should probably keep those in strings or `BigInt` if your environment supports it.
