### ISSUE TITLE
Columns marked as GENERATED ALWAYS are not omitted from Initializer and Mutator interfaces

### ISSUE THREAD

**Issue by mjwwit** [kristiandupont/kanel#450]
Values for columns marked as `GENERATED ALWAYS` can not be submitted as part of `INSERT` or `UPDATE` queries. Currently, however, they are marked as optional properties in the generated `Initializer` and `Mutator` interfaces. This means that they can still be given a value, which is incorrect.

I've located a previous issue about `GENERATED` columns, #21, which was fixed in commit a6feead0137eb717a209fce4346112df81bf7357. The omitting of `GENERATED ALWAYS` columns for `Initializer` and `Mutator` interfaces might have gotten lost in a refactor somewhere, as the code back then looked completely different.

**Comment by kristiandupont** [comment]
Ah, that might indeed have gone lost in the major rewrite to 3.0. Thanks for letting me know, I'll look into it!
