### ISSUE TITLE
Bug in generateIdentifierType function

### ISSUE THREAD

**Issue by sherazahmedch** [kristiandupont/kanel#455]
https://github.com/kristiandupont/kanel/blob/17bb3db9880d1faaa5703445c60352d150338072/packages/kanel/src/default-metadata-generators.ts#L82

The above mentioned line of code is wrong. It should be as follows:
`imports.push(...innerType.typeImports);`

In the absence of above mentioned correction only primitive types will work correctly with primary keys. But If I have a UUID as my primary key then the following configuration will fail:

```
 "pg_catalog.uuid": {
    name: "UUID",
    typeImports: [
      {
        name: "UUID",
        path: "crypto",
        isAbsolute: true,
        isDefault: false,
        importAsType: true,
      },
    ],
  },
```

**Comment by kristiandupont** [comment]
Thank you for this, nice catch! I've published a new version with the fix.
