### ISSUE TITLE
`kanel-knex` doesn't generate imports for Materialized Views

### ISSUE THREAD

**Issue by MarloDelatorre** [kristiandupont/kanel#458]
It generates the correct type declarations for Materialized Views, but it is missing the import lines for the Materialized Views

Looks like in type declarations code we access the different fields in `schema`: 
https://github.com/kristiandupont/kanel/blob/main/packages/kanel-knex/src/generateKnexTablesModule.ts#L132-L138

However, in the imports code we only access `schema.views`:
https://github.com/kristiandupont/kanel/blob/main/packages/kanel-knex/src/generateKnexTablesModule.ts#L101-L107

Feel free to close if I am mistaken, thanks!

**Comment by kristiandupont** [comment]
You are right, that looks like a bug! Thank you for informing me!

**Comment by kristiandupont** [comment]
There's a new version published with this fix. Thank you!

**Comment by MarloDelatorre** [comment]
No sir, thank you! 😄
