### ISSUE TITLE
Types

### ISSUE THREAD

**Issue by dmoose** [kristiandupont/kanel#5]
using the custom type map solved almost all the issues I had.  For some reason either I can't figure out the correct key to use or there is still a problem with Macaddr, Int4, and Float8.  Int4 and Float8 are aliases but Macaddr is a regular type and it worked for inet which seems strange.

**Comment by kristiandupont** [comment]
Hm, that's weird. Is it perhaps confusing that the system PascalCases types per default? They key in the typemap should be `macaddr`, could that be the issue?

**Comment by dmoose** [comment]
I tried a variety of versions including macaddr, mac_addr, in case it was a case issue.  For some reason they still came through as undefined.  Did a quick solve via shellscript replacement to make typescript happy.  I can do some more looking at it and see if I can get you better data or find a fix.

**Comment by kristiandupont** [comment]
That would be great. A quick experiment here with
```javascript
  customTypeMap: {
    macaddr: 'string'
  },
```
seems to work, but maybe something else is up. Let me know if you find something
