### ISSUE TITLE
generateIndex doesn't work with kanel-kysley?

### ISSUE THREAD

**Issue by taybin** [kristiandupont/kanel#516]
The index refers to things like FooInitializer from the kanel-kysley generated file, but that doesn't seem to exist.  It also doesn't export the Selectable, Insertable, and Updatable types.

Is there a way to make it work or do I need to provide my own generateIndex hook?

**Comment by kristiandupont** [comment]
Are you running the index hook as the last hook in the array?

**Comment by taybin** [comment]
@kristiandupont, no that resolved the issue.  Thank you.
