### ISSUE TITLE
kanel-kysely should include schema in Schema.ts output

### ISSUE THREAD

**Issue by taybin** [kristiandupont/kanel#521]
Given a schema named `reports`, with the table `users`, it should generate ReportsSchema.ts with contents:

```
export default interface ReportsSchema {
  'reports.users': UsersTable;
}
```

Without this, I need to include `withSchema()` on every query.  And `withSchema()` is deprecated when called on an `ExpressionBuilder`.

Or is there a clean way to enable this in kanelrc.js?

**Comment by taybin** [comment]
I tried to find a way to do this in the config, but ended up with a postRenderHook hack.  I don't actually have anything in the public schema, but would definitely need some extra handling for that.

```
const schemaRe = /(\w+):/;

function setSchemaName(path, lines) {
  let schema = '';
  if (path.includes('Schema.ts')){
    if (path.includes('SchemaA')) {
      schema = 'schemaa';
    } else if (path.includes('SchemaB')) {
      schema = 'schemab';
    }
    return lines.map(l => {
      const m = l.match(schemaRe);
      if (!m) {
        return l;
      }
      return l.replace(m[1], `'${schema}.${m[1]}'`);
    });
  }
  return lines;
}
```

**Comment by kristiandupont** [comment]
That's awesome! Sorry about not responding to this, it does look like this should be in the library. Maybe I can get around to that some time in the next months.

**Comment by taybin** [comment]
Not a problem!  This is open source, so I’m not complaining.

**Comment by DROFEL** [comment]
I faced the same problem and would like to help improve the library!

**Comment by taybin** [comment]
I can verify this works, but figuring out how to enable it took a little digging.  Thank you though!

**Comment by kristiandupont** [comment]
Great! You are obviously welcome to contribute to the README if you should like :-)
