### ISSUE TITLE
IDE error on import {type default as ....}?

### ISSUE THREAD

**Issue by dangnhdev** [kristiandupont/kanel#542]
I tried to research this, but I couldn't find anything about this syntax. Both VSCode and WebStorm show a file error for this. However, tsc compiles it normally.
![image](https://github.com/kristiandupont/kanel/assets/7861174/6c0bd3e3-9e83-4c12-a512-46fc454f2215)

How should I address this issue?

Here is my tsconfig.json and .kanelrc.cjs file:
https://gist.github.com/dangnhdev/e1946fcad3e02d55cd0a43cdce9157a6

**Comment by kristiandupont** [comment]
Could it be that you are running an older version of TSC in your IDE than what you have in your `package.json`?  Take a look at [this](https://stackoverflow.com/a/39676463/1417293) StackOverflow answer.

**Comment by kennethnym** [comment]
I am using the latest TypeScript (5.4.2) and can confirm this is an issue. WebStorm is picking up the correct version, so it is not an IDE issue. Is there a reason why the generated code prefixes each imported member with `type`, rather than making the entire import statement type only, since afaik the code will never import non-type members?

instead of:

```ts
import { type default as Table } from "..."
```

generate

```ts
import type { default as Table } from "..."
```

**Comment by kristiandupont** [comment]
So running `tsc` fails as well?

Kanel can generate enums which generate "code" as well as types, so those require regular importing. At least, I believe so -- I don't think I've ever actually verified this...

**Comment by thesmart** [comment]
I'm having the same issue, and also using Webstorm. I upgraded to the latest version which invalidated symbol caches to rerun the code indexer. This  seems to have fixed the `import { type default ` issue for me.

I will also note that `import { type` syntax may result in side-effects:

```typescript
import { type A, type B } from 'mod';

// is transpiled to

import {} from 'mod';
// which is the same as
import 'mod';
```

**Comment by kristiandupont** [comment]
This was recently brought to my attention and is a good reason to change the syntax, thank you! However, as I stated earlier, Kanel can in fact generate a bit of code if you use `enum`, so it would have to check for those. I am considering getting rid of enums altogether as I personally prefer union types but that might upset some people.

**Comment by kristiandupont** [comment]
I have just published a version that I think should fix this issue. Let me know if it works!
