### ISSUE TITLE
text[] issue on V2

### ISSUE THREAD

**Issue by kaliq-i** [kristiandupont/kanel#555]
Following this issue https://github.com/kristiandupont/kanel/issues/111 - I am unable to upgrade to v3 due to significant breaking changes, is there any recommendation you have for handling the text[] custom map. I've tried 

 `"pg_catalog.text[]": "string[]",`

with minimal success. Thanks!

**Comment by kaliq-i** [comment]
I am currently on v2.4.5 and unable to update in the near future. 
Without a customType, the output is text[] rather than string[]. text[] is not recognised by typescript. 

![image](https://github.com/kristiandupont/kanel/assets/41687116/81c76c53-e808-4d74-9522-ec241ae2db45)

**Comment by kristiandupont** [comment]
Ah ok, you want a solution for the old version, I misread that. Maybe try `text[]: string[]`. I don't quite remember..

**Comment by kaliq-i** [comment]
gave it a go unfortunately didnt work
tried text[]:string[] and below

![image](https://github.com/kristiandupont/kanel/assets/41687116/8956d66f-abef-464b-aec0-cfd34aee06f8)

**Comment by kaliq-i** [comment]
Any ideas, would be super helpful :)

**Comment by kristiandupont** [comment]
Sorry, I just don't remember how things work. I would recommend upgrading -- everything should still be possible like it was in the old version.

**Comment by kaliq-i** [comment]
Closed as I've migrated to v3
