### ISSUE TITLE
bytea example relies on `bytea` package which does not exist

### ISSUE THREAD

**Issue by juho** [kristiandupont/kanel#568]
hi,
the example for generating a bytea field relies on the `bytea` package which does not exist. was this a typo or am i possibly missing something? the one i can find is `postgres-bytea` which does not have TS types available.

**Comment by kristiandupont** [comment]
Ah sorry, I should perhaps make a note of that. The example is meant to show you how you can use a type that you import from somewhere, so I made the `bytea` package up. I don't actually know of any library that is suited for that particular type.

**Comment by kristiandupont** [comment]
I have updated the docs now
