### ISSUE TITLE
Self Reference

### ISSUE THREAD

**Issue by dmoose** [kristiandupont/kanel#6]
The example I left in issue 4 seems to be because of a self reference.  The table has a parentUuid that is a self reference so the generated file includes itself and creates a conflict with the ID.

Generated Example:

import { ConfigsId } from './configs';

import ConfigType from './config-type';

export type ConfigsId = number & { __flavor?: 'configs' };

export default interface Configs {
/**

    Primary key. Index: configs_pkey
    Index: idx_configs_on_config_UUID
    */
    uuid: ConfigsId;
    parentUuid: ConfigsId | null;

**Comment by kristiandupont** [comment]
Ah ok, yes, *that* is a case I hadn't thought of :-D Should be an easy fix though, I will look into that later today.

**Comment by kristiandupont** [comment]
I think this should work now. Try the new version and let me know.
