### ISSUE TITLE
Incorrect import path if importsExtension is not defined

### ISSUE THREAD

**Issue by litewarp** [kristiandupont/kanel#604]
If you leave importsExtension undefined, you get import paths like:
```
import type { UsersUserId } from './Usersundefined';
```

![image](https://github.com/user-attachments/assets/dc2d0ac1-aa71-49e8-8881-13e87c7e129c)

But if you add the importsExtension options, e.g., `importsExtension: ".js"` , everything is good.

![image](https://github.com/user-attachments/assets/5832462b-205d-41f1-9a35-c1c978cef2ed)

**Comment by kristiandupont** [comment]
My apologies! I've published a new version that should fix this.

**Comment by litewarp** [comment]
Awesome! Thanks!
