### ISSUE TITLE
kanel-knex@2.4.0 dependent on kanel-seeder not on npm

### ISSUE THREAD

**Issue by AudunWA** [kristiandupont/kanel#612]
The newly published kanel-knex@2.4.0 has kanel-seeder@1.0.0 as a dependency, but it's not on npm.

**Comment by kristiandupont** [comment]
Ouch, that was embarrassing! I'll get this fixed, but I don't have time today so I hope you can rely on the old version for now?

**Comment by AudunWA** [comment]
No worries :)

**Comment by kristiandupont** [comment]
This should now be fixed. Let me know if you have other issues!
