### ISSUE TITLE
More Detailed Docs?

### ISSUE THREAD

**Issue by Bradleykingz** [kristiandupont/kanel#7]
Anything other than the 'connection' object in ',kanelrc.js' isn't so easy to understand.

Would be great if the docs could be expanded a bit. If nothing else, to cover options in the README

**Comment by kristiandupont** [comment]
That's fair. The configuration options are rather limited so far but they should still be clearer. I will try and improve that.

**Comment by kristiandupont** [comment]
I've updated the README, hope that helps. Let me know if something is still unclear.
