### ISSUE TITLE
Transform function for file names

### ISSUE THREAD

**Issue by zth** [kristiandupont/kanel#71]
Thanks for a great project/tool!

Adding on to this issue https://github.com/kristiandupont/kanel/issues/18 I've often found myself wanting to transform the generated file name. 

What I'd like to do is really _prepend_ both the generated file names _and_ types with `Db_`, so `Db_Users.ts` -> `type Db_Users`, etc. This is all to help navigate my code bases which for various reasons tend to have a bunch of type representations for the same concept, but coming from/going to different sources (imagine I have a `User` type that has a representation in the DB I export through `kanel`, and then one for the User GraphQL type I return in my API, and then one for some other source, etc..).

What do you think about this idea? Does it make sense to you?

**Comment by kristiandupont** [comment]
Yes, that makes perfect sense. As you might have seen, I allow you to specify casing as a config option because I personally use dash-casing for my file names. Just like for the model names, the file names should be completely custom with a function like you suggest.

**Comment by zth** [comment]
Excellent! Do you want me to take a stab at implementing it?

**Comment by kristiandupont** [comment]
If you feel like it, certainly. I should warn you that the code is what started out as a small utility in a larger project that was then extracted, so it's severely under-tested :-)

I suppose this would be a major (as in "semver major") update that removes all the casing configuration options and replaces them with optional functions, something like:
```typescript
{
  modelNominator: (model: Model) => string,
  modelFileNominator: (model: Model) => string,
  typeNominator: (type: Type) => string,
  typeFileNominator: (type: Type) => string,
}
```

I would then expand upon that with nominators for initializers (as well as mutators which aren't even implemented yet) and id-types, but that should probably be a separate task :-)

Of course, this change isn't super trivial so I understand if you don't have the time or desire -- I'll get around to it soon, I hope.

**Comment by zth** [comment]
Ah right, that's slightly more involved than what I was planning on doing 😄 I guess I'll wait, looking forward to it!

**Comment by kristiandupont** [comment]
Alright, I've made an attempt now that's published. Instead of the casings options, you can now specify a `fileNominator` that should do what you're asking for. Try it out and let me know if it works for you!
