### ISSUE TITLE
v.1.0.0 and property casing

### ISSUE THREAD

**Issue by zth** [kristiandupont/kanel#74]
Hi!

I've just tried `1.0.0` and it does exactly what I want for custom file and model naming - excellent work 😄  However, it seems like `propertyCasing` is gone, which is something I was relying on (I'm using `slonik` configured to auto convert property names to camel case). Is there a way for me to implement that same functionality somehow using `1.0.0`?

**Comment by kristiandupont** [comment]
Argh, I was assuming nobody was using that and I wasn't myself anymore. No, that's not currently possible. You might want to revert to the previous version then and I will fix it. Not today though :-)

Happy new year!

**Comment by Ericnr** [comment]
It could be a `propertyNominator` that works just like the others

**Comment by zth** [comment]
@kristiandupont sorry to disappoint! 😄 Thank you! No stress, I'll remain on the old version for now. Thank you for your great work!

**Comment by kristiandupont** [comment]
Ok, this is fixed in 1.1.0. Let me know if it works!

**Comment by zth** [comment]
Works wonders! Thank you @kristiandupont ! 👏
