### ISSUE TITLE
Adjusting Initializer only types

### ISSUE THREAD

**Issue by vonadz** [kristiandupont/kanel#85]
Firstly, awesome job and thanks for your work! Is there a way to adjust the Initializer type for models? I'd like to be able to make all of the values in the initializer type optional, while keeping the main model type as is.

**Comment by kristiandupont** [comment]
Cheers :-)
Yes, I guess you could use something like what was suggested in #83 -- I just need to think that through a bit. (If you need a solution right now, the only way forward is with the existing hooks. They are not exactly elegant but you should be able to make it work).

**Comment by vonadz** [comment]
Oh I see. I think I misunderstood what the first argument of the modelHooks actually was. Thanks for the clarification :)
